### ISSUE TITLE
Python Memory Leak with MonoLoader in Standard Mode

### ISSUE THREAD

**Issue by owengc** [MTG/essentia#54]
Similar to this report:
https://github.com/MTG/essentia/issues/40

I am trying to open and analyze multiple files using the MonoLoader algorithm, but this results in a memory leak that keeps growing as more and more files are loaded. Here's the code I was using to get the durations of the audio files in my music library: (please correct me if there's a better way to do this, but I couldn't find anything in the documentation about 'unloading' a file once it's been loaded, or a way to open a different file with the same instance of MonoLoader/AudioLoader)

    import os
    import essentia 
    import essentia.standard
    import essentia.streaming

    from os.path import join, getsize

    extensions = dict()
    durations = []
    with open('durations.txt', 'wb') as f:
        for root, dirs, files in os.walk('/path/to/music/library'):
            if 'CVS' in dirs:
                dirs.remove('CVS')  # don't visit CVS directories
            #print sum(getsize(join(root, name)) for name in files),
            print 'album: {0}\n'.format(root)
            for name in files:
                if name.endswith(('.wav', '.aif', 'aiff', '.flac', '.mp3', '.m4a')):
                    #print root
                    # and then we actually perform the loading:
                    try:
                        loader = essentia.standard.MonoLoader(filename = join(root, name))
                        audio = loader()
                        duration_in_seconds = len(audio)/44100.
                        f.write('{0}, '.format(duration_in_seconds))
                        print '{0},'.format(duration_in_seconds),
                        #del loader #making these calls has no effect
                        #del audio #...
                        #gc.collect() #...
                    except (RuntimeError, TypeError, NameError):
                        #print 'could not parse file $s\n' % name
                        continue

**Comment by tcwalther** [comment]
I can confirm this bug still exists. It occurs both in MonoLoader and in AudioLoader, in standard mode (probably also in streaming mode). From how I see it, the audio file is not freed from memory. Like @justinsalamon, I would hit a big performance problem if I called an external script (beside the fact that that's a pretty ugly solution!).

**Comment by ctsssd** [comment]
During installation I got following error 
Building all the algorithms
Ignoring the following algorithms: AudioLoader, MonoLoader, EqloudLoader, EasyLoader, MonoWriter, AudioWriter, MetadataReader, GaiaTransform

So I am unable to access MonoLoader. Do you have any alternative.
I have tried following code and error.

>>> import essentia.standard
>>> import essentia.streaming
>>> loader = essentia.standard.MonoLoader()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'MonoLoader'

**Comment by dbogdanov** [comment]
@ctsssd You did not have libavformat/libavcodec/libavutil/libavresample installed on your system, therefore, Essentia was compiled without AudioLoader/...

**Comment by andimarafioti** [comment]
So this error is still out there and caused me some time loss. The solution provided by @tcwalther seems to work, but I don't fully understand it and it causes my computer to max all four processors and use a ton of run while the program is running.

**Comment by andimarafioti** [comment]
I looked into the fork thing and got it to work 'better' (IMO). The changed @tcwalther code:
```
new_pid = os.fork()
if new_pid == 0:  # don't omit this if-clause! If new_pid == 0, then we're in the forked process.
    try:  # use a try..except..finally cause to make sure you _always_ terminate the process
        # your leaking code
    except Exception:
        pass  # do your exception handling here if you like
    finally:
        os._exit(0)  # close fork and return to parent process
else:
    child = new_pid # this is what the parent process does
os.waitpid(child, 0) # the whole code waits for the child process to end
```

My code actually loads a big database and the MonoLoader was inside of this loop, so by not restricting the number of fork() it would just keep on creating parallel processes until the computer collapsed.

**Comment by tcwalther** [comment]
@andimarafioti ah true; in my code I didn't have to do it cause my function was working stuff off a queue, and the next item would only be picked off the queue once the forked process was finished, thus leaving the main thread unoccupied.

It turns out there's also another, less verbose solution. On Unix (Mac/Linux), `multiprocessing.Process` forks under the hood. So you can write:

    p = Process(target=function_executing_monoloader, args=(some, arguments, you, want, to, pass))
    p.start()
    p.join()

**Comment by jlyda** [comment]
This issue is fixed in commit 2436db3b11dfbb55339298123752071fcde07fac

**Comment by justinsalamon** [comment]
@dbogdanov has this actually been fixed? I'm running 2.1-dev via python and still getting a pretty nasty memory leak with EasyLoader.

**Comment by aaronabebe** [comment]
Hi! I'm also still experiencing this issue with a `MonoLoader` in version `2.1b6.dev1110`. After a few concurrent open files in the same process my script errors with: 

```sh
RuntimeError: Error while configuring MonoLoader: AudioLoader: Could not find stream information, error = End of file
```
